Update Trezor to 9.0.11 (#1882)
* Update Trezor to 9.0.11

Getting error:

TypeError: Cannot destructure property 'BridgeV2' of 'transport_1.default' as it is undefined.

This seems to have changed recently (within the last couple of days) as this is breaking in one of our automated tests.

Info:

@trezor/connect v9.0.7

How to reproduce
This happens consistently when trying to import the module.


Update to 9.0.11 should solve this

* Update package.json version to 2.4.3-alpha.1

---------

Co-authored-by: Kat Leight <33187102+leightkt@users.noreply.github.com>